# Generated by Django 4.0.4 on 2022-05-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='status',
            field=models.CharField(choices=[('docked', 'Docked'), ('outbound_to_sea', 'Outbound to Sea'), ('inbound_to_harbour', 'Inbound to Harbour'), ('maintenance', 'Maintenance')], default='docked', max_length=50),
        ),
    ]
